codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 1
      carball:
        threshold: 0.5
        flags: hiddenfigures
    patch: off
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no


flags:
  # filter the folder(s) you wish to measure by that flag
  carball:
    # only include files in the backend folder
    paths:
      - "!hiddenfigures/tests"
      - hiddenfigures/*
ignore:
  - tests/*
  - hiddenfigures/tests/*
  - utils/tests/*
  - init.py
  - setup.py
  - command_line.py
  - hiddenfigures/controls/*

